In [1]:
import numpy as np

In [6]:
# load validation data from /Users/sultandaniels/Documents/Transformer_Kalman/outputs/GPT2/240619_070456.1e49ad_upperTriA_gauss_C/data/val_upperTriA_gauss_C.pkl
val_data = np.load('/Users/sultandaniels/Documents/Transformer_Kalman/outputs/GPT2/240619_070456.1e49ad_upperTriA_gauss_C/data/val_upperTriA_gauss_C.pkl', allow_pickle=True)
print(len(val_data))

6000


In [9]:
print(val_data[0].keys())

dict_keys(['states', 'obs', 'A', 'C'])


In [13]:
A0 = val_data[0]['A']
#check if A0 is upper triangular
print("np.all(np.triu(A0) == A0) is ", np.all(np.triu(A0) == A0))

for i in range(len(val_data)):
    A = val_data[i]['A']
    if not np.all(np.triu(A) == A):
        print("A is not upper triangular")
        print(i)
        break
print("All A are upper triangular")



np.all(np.triu(A0) == A0) is  True
All A are upper triangular


In [3]:


# # Example arrays
# array = np.random.rand(3, 2, 4)  # (3, 200, 251) array
# divisor = np.random.rand(3)          # (3) array

# print("array", array)
# print("divisor", divisor)

# result_2 = np.zeros_like(array)
# for i in range(array.shape[0]):
#     result_2[i] = array[i] / divisor[i]

# print("result_2", result_2)
# # Element-wise division across axis 0 using broadcasting
# result = array / divisor[:, np.newaxis, np.newaxis]

# print("result", result)

array [[[0.18960546 0.04282465 0.16142484 0.19674476]
  [0.39188079 0.23064968 0.05314969 0.68640221]]

 [[0.09587213 0.58825714 0.93439877 0.95156362]
  [0.21806364 0.70914652 0.05904838 0.9130775 ]]

 [[0.79584719 0.40109639 0.18576027 0.44005899]
  [0.85885428 0.22000314 0.29155903 0.52291018]]]
divisor [0.35409767 0.67480933 0.7730006 ]
result_2 [[[0.53546093 0.12094021 0.4558766  0.55562286]
  [1.10670254 0.65137307 0.15009895 1.93845449]]

 [[0.14207291 0.8717383  1.38468562 1.41012222]
  [0.32314853 1.05088429 0.0875038  1.35308962]]

 [[1.02955571 0.51888238 0.24031064 0.56928674]
  [1.11106547 0.28460927 0.37717827 0.676468  ]]]
result [[[0.53546093 0.12094021 0.4558766  0.55562286]
  [1.10670254 0.65137307 0.15009895 1.93845449]]

 [[0.14207291 0.8717383  1.38468562 1.41012222]
  [0.32314853 1.05088429 0.0875038  1.35308962]]

 [[1.02955571 0.51888238 0.24031064 0.56928674]
  [1.11106547 0.28460927 0.37717827 0.676468  ]]]
